## I NEVER rrecomment adding you secrets to your code repositiyr, so you shold be safely able to put yourkeys in this file directly, as is shows in the development section,  but sometimes you might need to.  In that case
# you can use the envrironment variable metod in the production production.
development:
  omniauth_provider_key: << Provider Key>> 
  omniauth_provider_secret: << Provider Secret >>
  domain_name: lvh.me
  secret_key_base: 6ec9ae65d4de59aa1a79c800d887721258686e4f99905c53a264ffd8255a601d7417b1ed7d4cef67f359e373472f0160aeb9698fa69578a1497b5b99209afd0e

test:
  secret_key_base: 63bea79c82bf315c9583c9fca8a2adc74a3706f9f0ea98956d2e73a526faef1e8b18b01d1103e4ee0d64c0fb7c75ac4dfca758bcb2e8d6ef700ae6e9a62ef0b7

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
